main:
	gcc -o main main.c LLinearSimples.c LCircularSimples.c LLinearDupla.c FIFO.c LIFO.c InterfaceGrafica.c -I$(PWD)/gfx -L$(PWD)/gfx -lgfx -lSDL -lSDL_gfx -lSDL_ttf -Wall -Wextra -pedantic

clean:
	rm main *~
